# ORG_06_VISUAL_SYSTEM.yaml (Phase II — optional)

meta:
  owner: "AI Opener"
  version: "2.0.0"
  last_updated: "2026-01-08"
  purpose: "Visual rules and design QA (ORG defaults)"
  notes: "ORG is the default visual baseline (self-sufficient). CLIENT may optionally override when the user activates a client context. SSOT stores rules + pointers only (no images)."
  tags: [org, ssot]

visual_system:
  description: "ORG-default visual DNA, rules, and QA. Self-sufficient baseline; CLIENT may override when activated."
  visual_dna_schema:
    required_fields:
      - dna_caption
      - style_keywords
      - palette
      - composition
      - lighting
      - textures_materials
      - backgrounds
      - do_dont
      - negative_prompts
      - external_reference_sets
    field_descriptions:
      dna_caption: "1–3 sentences capturing the visual essence (what it should feel like)."
      style_keywords: "Fixed keywords that steer look & vibe."
      palette: "Named colors with HEX + usage rules; includes forbidden colors."
      composition: "Layout rules: whitespace, framing, subject placement."
      lighting: "Lighting intent: soft/hard, natural/studio, shadow behavior."
      textures_materials: "Preferred textures/materials + avoid list."
      backgrounds: "Allowed background types; forbidden background types."
      do_dont: "Explicit do/don’t rules."
      negative_prompts: "Brand negatives to reduce variance."
      external_reference_sets: "Pointers only (IDs/URLs); no images stored in SSOT."

  visual_dna_default:
    dna_caption: "Premium, minimal, Dutch professional-services look: calm, credible, modern, with generous whitespace and restrained color use."
    style_keywords: ["premium", "minimal", "editorial", "clean", "credible", "calm", "modern", "high-end", "subtle"]
    palette:
      primary:
        - name: "Deep Navy"
          hex: "#0B1F3B"
          usage: "Primary accents, headings, key shapes."
      secondary:
        - name: "Warm Gray"
          hex: "#8A8F98"
          usage: "Secondary accents, UI-like elements."
      neutrals:
        - name: "Off White"
          hex: "#F7F7F5"
          usage: "Background base."
        - name: "Charcoal"
          hex: "#1A1D21"
          usage: "High-contrast elements (avoid literal text overlays)."
      forbidden:
        - name: "Neon Green"
          hex: "#39FF14"
          reason: "Too loud / non-premium."
        - name: "Hot Pink"
          hex: "#FF2D95"
          reason: "Too playful / non-enterprise."

    composition:
      whitespace: "High"
      framing: "Rule of thirds; clear focal point; avoid clutter"
      subject_scale: "Medium-large subject, ample negative space"
      camera_angle_defaults: ["eye-level", "30-degree", "top-down (only for flatlay)"]
      avoid: ["busy layouts", "crowded scenes", "multiple focal points"]

    lighting:
      intent: "Soft, natural-feeling or soft studio; diffused shadows"
      avoid: ["harsh flash", "hard shadows", "over-saturated HDR look"]

    textures_materials:
      prefer: ["matte finishes", "paper grain subtle", "soft textiles", "natural wood", "brushed metal (subtle)"]
      avoid: ["chrome shine", "plastic glossy", "neon gradients"]

    backgrounds:
      allowed: ["clean minimal", "soft neutral", "subtle texture", "executive interior (uncluttered)"]
      forbidden: ["busy patterns", "cheap stock backdrops", "neon gradient walls"]

    do_dont:
      do:
        - "Keep compositions calm and uncluttered"
        - "Use restrained contrast and consistent lighting"
        - "Maintain premium realism (no obvious AI artifacts)"
      dont:
        - "No text overlays in the image"
        - "No exaggerated surrealism unless explicitly requested"
        - "No chaotic color palettes"

    negative_prompts:
      brand:
        - "no neon colors"
        - "no harsh shadows"
        - "no clutter"
        - "no cheesy stock-photo look"
        - "no visible text overlays"
        - "no distorted hands/faces"
        - "no warped geometry"

    external_reference_sets:
      policy: "Pointers only; images live outside SSOT."
      default_refsets: []
      pointer_format_examples:
        - "refset_org_premium_minimal_v1"
        - "https://assets.company.com/refsets/org/premium-minimal/v1"

  external_reference_policy:
    store_images_in_ssot: false
    allowed_pointer_types: ["refset_id", "https_url"]
    rules:
      - "SSOT stores only pointers/IDs/URLs and short captions."
      - "If a pointer requires auth, store only the refset_id; auth handled by runtime."
      - "Never paste base64 or binary data into SSOT."

  nano_banana_defaults:
    engine: "nano-banana"
    num_images_range: [1, 4]
    batch_size: 4
    allowed_aspect_ratios: ["1:1", "4:5", "3:4", "16:9", "9:16"]
    allowed_resolutions: ["1k", "2k", "4k"]
    allowed_output_formats: ["png", "jpeg", "webp"]
    aspect_ratio_policy: "Match channel defaults unless user specifies"
    reproducibility_policy: "No seeds. Consistency comes from curated external reference sets (refset_id/URL) and iterative edits."
    constraints_policy: "Nano-Banana does not support negative prompts; treat negative_prompts as brand constraints that must be translated into positive instructions."
    safety: "Enterprise-safe by default; avoid sensitive/controversial visuals unless explicitly requested"

  output_package_contract:
    must_return:
      - "effective_visual_dna_version"
      - "brief_summary"
      - "nano_banana_payload"
      - "refset_pointers_used"
      - "params_used"
      - "qa_check_passfail"
    format_rules:
      - "Return payload and params inside code blocks."
      - "Never embed images in SSOT; only return external URLs/IDs if available."

design_qa:
  description: "Design QA checklist (ORG default). Used to validate brand-fit before acceptance."
  checklist:
    - "Palette matches ORG/CLIENT rules (no forbidden colors)."
    - "Composition is minimal; strong focal point; ample whitespace."
    - "Lighting is soft/diffused; no harsh flash or hard shadows."
    - "No visible text overlays unless explicitly requested."
    - "No obvious AI artifacts (hands, faces, warped geometry)."
    - "Background is clean and not cluttered."
    - "Materials feel premium (avoid glossy plastic/chrome)."
    - "Visual aligns with dna_caption vibe (credible, calm, modern)."
    - "Avoid cheesy stock-photo aesthetics."
    - "Channel fit: crop/aspect ratio supports intended placement."
    - "If people present: natural proportions, neutral professional styling."
    - "If product present: accurate shape, clean silhouette, no melted edges."
